config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  root 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :feeds do
     collection do
        post :confirm
      end
    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :content,  presence: true
  validates :image,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :feeds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def authenticate_user
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  def index
    @feeds = Feed.all
  end
  
  def show
  end

  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  def confirm
    @feed = Feed.new(feed_params)
  end

  def edit
  end

  def create
      @feed = Feed.new(feed_params)
      @feed.user_id = current_user.id
      if params[:back]
        render :new
      else
        if @feed.save
          redirect_to feeds_path, notice: "Post was successfully created."
        else
          render :new
        end
      end
    end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_feed
    @feed = Feed.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(:image, :image_cache, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'Login Failed!'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'Logged out!'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_feeds_path
    elsif action_name == 'edit'
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true, url: choose_new_or_edit ) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>
      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="signupform">
  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div><br>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div><br>

  <div class="actions">
    <%= form.submit "Create Post" %>
  </div>
  </div>
<% end %>

app/views/feeds/confirm.html.erb
<div id="wrapper">
  <div id="contents">
  <h1>Send with the following contents.</h1>
<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
  <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <p class="showp">Content:<%= @feed.content %></p>
  <%= form.submit "Post" %>
<% end %>

<%= form_with(model:@feed, url:new_feed_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "Back", name: "back" %>
<% end %>
</div>
</div>

app/views/feeds/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', feed: @feed %>
<button type="button"><%= link_to 'Detail', @feed %></button>
<button type="button"><%= link_to 'Back', feeds_path %></button>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Posts</h1><br>
<table class="picture">
  <div class="row">
    <% @feeds.each do |feed| %>
      <div class="btn-group btn-group-sm">
        <div class="col-md-12"><p class="showp">Username: <%= feed.user.name %></p></div>
        <div class="col-md-12 posted_comment"><p class="showp">Content：<%= feed.content %></p></div>
        <div class="col-md-12 posted_picture"><%= image_tag "#{feed.image}" %></div>
        <button type="button" class="btn btn-info"><%= link_to 'Detail', feed %></button>
        <button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_feed_path(feed) %></button>
        <button type="button" class="btn btn-danger"><%= link_to 'Delete', feed, method: :delete, data: { confirm: 'Are you sure?' } %></button>
      </div>
    <% end %>
  </div>
  <br>
  <button type="button" class="btn btn-info"><%= link_to 'New Post', new_feed_path %></button>
</table>

app/views/feeds/new.html.erb
<h1>New Post</h1>
<%= render 'form', feed: @feed %>
<button type="button" class="showb"><%= link_to 'Back', feeds_path %></button>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>
<p class="showp">
  <strong>Image:</strong>
  <%= image_tag @feed.image.url %>
</p class="showp">
<p>
  <strong>Content:</strong>
  <%= @feed.content %>
</p>

<button type="button" class="btn btn-primary btn-sm"><%= link_to 'Edit', edit_feed_path(@feed) %></button>
<button type="button" class="btn btn-info btn-sm"><%= link_to 'Back', feeds_path %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width">
  </head>
  <body>
    <div class="container">
     <div class="left">
       <nav class="navbar navbar-dark bg-light fixed-top">
        <span class="navbar-brand mb-0 h1">facebook clone</span>
       <p class="fbp">FacebookClone helps you connect and share with</p>
       <p class="fbp">the people in your life.</p>
       </nav>
     </div>
     <div class="right">
   <% flash.each do |key, value| %>
     <%= content_tag(:div, value, class: "#{key}") %>
   <% end %>
   <% if logged_in? %>
     <button type="button" class="btn btn-info"><%= link_to "Profile", user_path(current_user.id) %></button>
     <button type="button" class="btn btn-warning"><%= link_to "Logout", session_path(current_user.id), method: :delete %></button>
     <button type="button" class="btn"><%= link_to "Posts", feeds_path(current_user.id) %></button>
   <% else %>
     <button type="button" class="btn btn-info"><%= link_to "Sign up", new_user_path %></button>
     <button type="button" class="btn btn-warning"><%= link_to "Login", new_session_path %></button>
   <% end %>
      <%= yield %>
     </div>
   </div>
   <div class="footerdiv">
     <footer>
       <p>English (UK) မြန်မာဘာသာ ภาษาไทย 中文(简体) Bahasa Melayu 日本語 العربية Bahasa Indonesia Español Português (Brasil) Français (France) <button type="button"class="btnplus">+</button></p>
       <br>
       <p>Sign-Up Log-In Messenger Facebook-Lite Watch People Pages Page-categories Places Games Locations Marketplace Facebook Pay Groups Oculus Portal Instagram Local Fundraisers Services Voting Information Centre About</p>
       <p>Create-ad Create Page Developers Careers Privacy Cookies AdChoices Terms Help Settings Activity log</p>
       <p>FacebookClone © 2020</p>
     </footer>
   </div>
 </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
<div class="signupform">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
<br>
  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
<br>
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
<br>
  <div class="field">
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>
</div>
<br>
  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing Account</h1>
<%= render 'form', user: @user %>

<td><button type="button" class="showback"><%= link_to 'Show', @user %></button></td>
<td><button type="button" class="showback"><%= link_to 'Back', users_path %></button></td>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Accounts</h1>
<br>
<table class="container">
  <div class="row">
    <% @users.each do |user| %>
      <ul class="btn-group btn-group-sm">
        <li class="col-md-12"><h4>Username: <%= user.name %></h4></li>
        <li class="col-md-12"><h4>Email: <%= user.email %></h4></li>
      </ul>
        <button type="button" class="btn btn-info"><%= link_to 'Show', user %></button>
        <button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_user_path(user) %></button>
        <button type="button" class="btn btn-danger"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></button>
      <br>
    <% end %>
  </div>
  <br>
  <button type="button" class="btn btn-info new_user"><%= link_to 'Create New Account', new_user_path %></button>
</table>

app/views/users/new.html.erb
<h2>Create Your New Account</h2>
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p class="showp">
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p class="showp">
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<button type="button" class="btn btn-primary btn-sm"><%= link_to 'Edit', edit_user_path(@user) %></button>
<button type="button" class="btn btn-info btn-sm"><%= link_to 'Back', users_path %></button>